set -g window-status-current-style fg=green,bold
set -g status-style bg=black,fg=brightwhite
set -g pane-border-style fg=brightblack

set -sa terminal-features ",xterm*:RGB"
set -g default-terminal "tmux-256color"

set -g allow-passthrough on
set -g detach-on-destroy off
set -g escape-time 0
set -g focus-events on
set -g history-limit 5000
set -g mouse on
set -g renumber-windows on

set -g mode-keys vi
set -g status-keys vi

set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind < swap-window -d -t -1
bind > swap-window -d -t +1

bind c new-window -c "#{pane_current_path}"

bind C command-prompt -p "session name:" { new-session -A -s "%%" }
bind X confirm-before -p "kill session? (y/n)" kill-session

bind R run-shell "tmux source-file ~/.tmux.conf"
